Move benchmarks to separate module
michaelbull/kotlin-result pull request #41
Opened 2020-11-28 20:30 UTC by hanleyt

PR for #38.

I'm new to kmp libraries and was doing some guessing with the source set config. Let me know if this is what you were thinking @Munzey!

2020-11-28 22:46 UTC, michaelbull commented
This looks great. Massively simplifies the main subprojects Gradle configuration too. Ping @Munzey for a review but LGTM 👍

2020-11-30 11:31 UTC, Munzey requested changes
Thanks again for taking a look at this!
Couple of suggestions

2020-11-30 11:31 UTC, Munzey commented on kotlin-result/build.gradle.kts
> -sourceSets.create("benchmark")
see this thread from when I was converting this build to mpp originally: https://github.com/michaelbull/kotlin-result/pull/18#discussion_r436006070

I recall running into issues trying to get the benchmark plugin to register any benchmark source when it existed inside the mpp project. 
Defining the "jvmBenchmark" source set alone wasn't enough. I believe I tried to create it as a custom source set inside of the mpp plugin: https://kotlinlang.org/docs/reference/mpp-dsl-reference.html#custom-source-sets. But that nothing was being registered as a target by the benchmark plugin. The multiplatform plugin turned out to provide a sort of workaround which may not be needed anymore. By calling `withJava()` inside the mpp `jvm` block, java code in the jvmBenchmark sourceset was magically picked up when registered to the benchmark plugin.

So you can definitely remove `withJava()` from this file, as well as `val jvmMain by getting` as that was only needed for the jvmBenchmark dependencies.

but perhaps some experimentation is needed to see what's the minimum needed to get this working for the new file

2020-11-30 11:31 UTC, Munzey commented on benchmarks/build.gradle.kts
> +sourceSets.create("benchmark")
as mentioned, this can go

2020-11-30 11:31 UTC, Munzey commented on benchmarks/build.gradle.kts
> +        withJava()
ditto, can remove this.

2020-11-30 11:31 UTC, Munzey commented on benchmarks/build.gradle.kts
> +        register("jvmBenchmark")
so at the time of converting to mpp, we only targeted jvm. But now there is a js target, and as we can see from the benchmark plugin description: https://github.com/Kotlin/kotlinx-benchmark
this should work for javascript too.

could we reorganize and move the benchmark code into `commonBenchmark`? 
I dont believe there is really anything in the current benchmark file that is jvm specific.

They have a great example for a multiplatform benchmark in the plugin repo, 
we can see the imports we would need to change here to make them multiplatform compatible: https://github.com/Kotlin/kotlinx-benchmark/blob/master/examples/kotlin-multiplatform/src/commonMain/kotlin/CommonBenchmark.kt

the build script for that example is also helpful: https://github.com/Kotlin/kotlinx-benchmark/blob/master/examples/kotlin-multiplatform/build.gradle

2021-01-30 18:53 UTC, michaelbull commented
Hi @Munzey & @hanleyt, can you shed some light on what the status of this PR is? Is it ok to merge or do we need to make some fixes before?

2021-02-01 18:28 UTC, Munzey commented
@michaelbull it would be great to just get some of the minor comments cleaned up before merging.
Although the switch to a `commonBenchmark` could be moved to a separate issue.
@hanleyt if your busy I got some time this week I can finish this pr if you like?

2021-02-08 17:26 UTC, Munzey commented
This can now be closed as it is continued in #47

2021-02-10 22:09 UTC, closed without merging